import { UserProfile } from '@/types/auth';
import { SavedCard } from '@/types/payments';
import { Model, Project } from '@/types/project';

const commonModels = {
  utility: [{ provider: 'openai', model: 'gpt-3.5-turbo' } as Model],
  low: [{ provider: 'openai', model: 'gpt-4o' } as Model],
  medium: [{ provider: 'anthropic', model: 'claude-3-sonnet' } as Model],
  high: [{ provider: 'openai', model: 'gpt-4-turbo' } as Model],
  super: [{ provider: 'openai', model: 'gpt-4o' } as Model],
  backup: [{ provider: 'deepseek', model: 'deepseek-7b' } as Model],
};

// A reusable set of fake projects for development mode.
// You can add more variety here to test different UI states.
export const FAKE_PROJECTS: Project[] = [
  {
    _id: 'proj_1',
    name: 'E-commerce AI Assistant',
    status: 'running',
    desiredStatus: 'stopped',
    ownerId: 'user_1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    maxCost: 23.45,
    maxRuntime: 32,
    runtime: 9000,
    cost: 5,
    lifetimeCost: 20,
    lifetimeRuntime: 4000,
    completeIssues: 8,
    incompleteIssues: 2,
    description: 'AI system assisting with product listing and customer support.',
    stars: 58,
    repositories: [
      { url: 'https://github.com/example/ecommerce-ai' },
      { url: 'https://github.com/example/ecommerce-ai-backend' },
    ],
    lastError: '',
    currentlyDoing: 'Processing customer queries',
    totalInputTokens: 125000,
    totalOutputTokens: 87000,
    pendingSensitiveRequest: null,
    history: [
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
        sender: 'user',
        type: 'status_update',
        content: 'Started initial deployment',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
        sender: 'agent',
        type: 'message',
        content: 'Deployment succeeded. Preparing tasks.',
      },
      {
        timestamp: '',
        sender: 'system',
        type: 'usage_cost',
        content: '',
      },
    ],
    models: commonModels,
    installations: [
      { name: 'openai' },
      { name: 'node:18' },
    ],
    testLevel: 'none',
    requestType: 'auto',
  },
  {
    _id: 'proj_2',
    name: 'Slack Finance Bot',
    status: 'starting',
    desiredStatus: 'running',
    ownerId: 'user_2',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    maxCost: 0.45,
    maxRuntime: 12,
    runtime: 180,
    cost: 5,
    lifetimeCost: 20,
    lifetimeRuntime: 4000,
    completeIssues: 1,
    incompleteIssues: 3,
    description: 'Bot that summarizes financial metrics in Slack.',
    stars: 9,
    repositories: [{ name: 'finance-bot', isPrivate: true }],
    lastError: '',
    currentlyDoing: 'Pulling container image',
    totalInputTokens: 22000,
    totalOutputTokens: 16500,
    pendingSensitiveRequest: null,
    history: [
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        sender: 'user',
        type: 'status_update',
        content: 'Created project and configured secrets.',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
        sender: 'system',
        type: 'system_event',
        content: 'Container image is being pulled.',
      },
    ],
    models: {
      ...commonModels,
      high: [{ provider: 'anthropic', model: 'claude-3-opus' }],
    },
    installations: [
      { name: 'slack_sdk' },
      { name: 'python:3.11' },
    ],
    testLevel: 'none',
    requestType: 'auto',
  },
  {
    _id: 'proj_3',
    name: 'Video Transcoder',
    status: 'stopping',
    desiredStatus: 'stopped',
    ownerId: 'user_3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    maxCost: 7.2,
    maxRuntime: 23,
    cost: 7.2,
    lifetimeCost: 20349,
    lifetimeRuntime: 29123400,
    runtime: 10800,
    completeIssues: 11,
    incompleteIssues: 1,
    description: 'Converts video formats using FFMPEG pipeline.',
    stars: 34,
    repositories: [{ url: 'https://github.com/example/video-transcoder' }],
    lastError: '',
    totalInputTokens: 500,
    totalOutputTokens: 200,
    pendingSensitiveRequest: null,
    history: [
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
        sender: 'user',
        type: 'message',
        content: 'Run stopped. Preparing to stop.',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        sender: 'system',
        type: 'status_update',
        content: 'Shutting down resources.',
      },
    ],
    models: commonModels,
    installations: [
      { name: 'ffmpeg' },
      { name: 'fluent-ffmpeg' },
    ],
    testLevel: 'none',
    requestType: 'change',
  },
  {
    _id: 'proj_4',
    name: 'Resume Parser API',
    status: 'stopped',
    desiredStatus: 'stopped',
    ownerId: 'user_4',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    maxCost: 18.0,
    runtime: 20000,
    maxRuntime: 45,
    cost: 5,
    lifetimeCost: 20,
    lifetimeRuntime: 4000,
    completeIssues: 20,
    incompleteIssues: 0,
    description: 'Extracts structured data from uploaded resumes.',
    stars: 112,
    repositories: [{ url: 'https://github.com/example/resume-parser' }],
    lastError: '',
    currentlyDoing: 'Shutting down pipeline',
    totalInputTokens: 45000,
    totalOutputTokens: 32000,
    pendingSensitiveRequest: null,
    history: [
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 29).toISOString(),
        sender: 'user',
        type: 'message',
        content: 'stopped QA testing.',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        sender: 'system',
        type: 'status_update',
        content: 'Marked project as stopped.',
      },
    ],
    models: {
      ...commonModels,
      utility: [{ provider: 'openrouter', model: 'command-r+' }],
    },
    installations: [
      { name: 'pdfminer.six' },
      { name: 'spacy' },
    ],
    testLevel: 'none',
    requestType: 'bug',
  },
  {
    _id: 'proj_5',
    name: 'HR Metrics Dashboard',
    status: 'error',
    desiredStatus: 'stopped',
    ownerId: 'user_5',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    maxCost: 4.75,
    maxRuntime: 43,
    cost: 5,
    lifetimeCost: 20,
    lifetimeRuntime: 4000,
    runtime: 4000,
    completeIssues: 6,
    incompleteIssues: 5,
    description: 'Visual dashboard of team performance and growth.',
    stars: 21,
    repositories: [{ name: 'hr-dashboard', isPrivate: false }],
    lastError: 'Build step failed due to missing env variable.',
    totalInputTokens: 500,
    totalOutputTokens: 200,
    pendingSensitiveRequest: null,
    history: [
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        sender: 'system',
        type: 'system_event',
        content: 'Deployment triggered.',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        sender: 'system',
        type: 'status_update',
        content: 'Build failed: Missing env var `DB_URL`',
      },
    ],
    models: commonModels,
    installations: [
      { name: 'react' },
      { name: 'chart.js' },
    ],
    testLevel: 'standard',
    requestType: 'dev',
  },
  {
    _id: 'proj_6',
    name: 'DevOps Onboarding Agent',
    status: 'pending',
    desiredStatus: 'running',
    ownerId: 'user_6',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    maxCost: 0,
    cost: 5,
    lifetimeCost: 20,
    lifetimeRuntime: 4000,
    runtime: 0,
    maxRuntime: 0,
    completeIssues: 0,
    incompleteIssues: 2,
    description: 'Guides new engineers through dev setup with automation.',
    stars: 0,
    repositories: [{ name: 'onboarding-agent', isPrivate: true }],
    lastError: '',
    currentlyDoing: 'Waiting for env vars',
    totalInputTokens: 31000,
    totalOutputTokens: 15000,
    pendingSensitiveRequest: null,
    history: [
      {
        timestamp: new Date().toISOString(),
        sender: 'user',
        type: 'sensitive_request',
        content: 'Requested access to internal Slack workspace.',
      },
    ],
    models: commonModels,
    installations: [
      { name: 'pyyaml' },
      { name: 'dotenv' },
    ],
    testLevel: 'required',
    requestType: 'production',
  },
];

export const FAKE_USER: UserProfile = {
  _id: 'test-user-id',
  email: 'dev-user@prompttosoftware.io',
  name: 'devuser',
  avatarUrl: '/avatar.png',
  isNewUser: true,
  balance: 100.00,
  role: 'user',
  integrations: {
    jira: { isLinked: false },
  },
  apiKeys: [
    { provider: 'OPENAI', api_key: 'sk-xxxxxx' },
    { provider: 'GOOGLE', api_key: 'AIzaSyxxxxxx' },
  ],
  starredProjects: [],
  accountStatus: 'healthy',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

import { ProjectSummary } from '@/types/project';
import { Transaction, TransactionStatus, TransactionType } from '@/types/transactions';

const baseModels = {
  utility: [{ provider: 'openai', model: 'gpt-3.5-turbo' } as Model],
  low: [{ provider: 'openai', model: 'gpt-4o' } as Model],
  medium: [{ provider: 'anthropic', model: 'claude-3-sonnet' } as Model],
  high: [{ provider: 'openai', model: 'gpt-4-turbo' } as Model],
  super: [{ provider: 'openai', model: 'gpt-4o' } as Model],
  backup: [{ provider: 'deepseek', model: 'deepseek-7b' } as Model],
};

export const FAKE_EXPLORE_PROJECTS: ProjectSummary[] = [
  {
    _id: 'explore_proj_1',
    name: 'AI Marketing Assistant',
    status: 'stopped',
    stars: 144,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    incompleteIssues: 1,
    completeIssues: 17,
    repositories: [{ url: 'https://github.com/example/ai-marketing' }],
    user: { _id: 'creator_1', name: 'Jess Wang', avatarUrl: '/avatars/jess.png' },
    starredByCurrentUser: true,
    models: baseModels,
  },
  {
    _id: 'explore_proj_2',
    name: 'Smart Meeting Notes',
    status: 'running',
    stars: 67,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    incompleteIssues: 2,
    completeIssues: 10,
    repositories: [
      { url: 'https://github.com/example/meeting-notes' },
      { name: 'meeting-ai-backend', isPrivate: false },
    ],
    user: { _id: 'creator_2', name: 'Leo Tran', avatarUrl: '/avatars/leo.png' },
    starredByCurrentUser: false,
    models: {
      ...baseModels,
      high: [{ provider: 'anthropic', model: 'claude-3-opus' }],
      medium: [
        { provider: 'anthropic', model: 'claude-3-opus' },
        { provider: 'openai', model: 'chatgpt-o' },
        { provider: 'deepseek', model: 'r1-reasoner' },
        { provider: 'anthropic', model: 'claude-3-opus' },
      ]
    },
  },
  {
    _id: 'explore_proj_3',
    name: 'Code Review Agent',
    status: 'running',
    stars: 93,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    incompleteIssues: 4,
    completeIssues: 9,
    repositories: [{ url: 'https://github.com/example/code-review-agent' }],
    user: { _id: 'creator_3', name: 'Riya Patel', avatarUrl: '/avatars/riya.png' },
    starredByCurrentUser: false,
    models: {
      ...baseModels,
      utility: [{ provider: 'openrouter', model: 'llama-3-8b' }],
    },
  },
  {
    _id: 'explore_proj_4',
    name: 'Personalized Learning Agent',
    status: 'running',
    stars: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), // recent
    updatedAt: new Date().toISOString(),
    incompleteIssues: 3,
    completeIssues: 1,
    repositories: [{ url: 'https://github.com/example/learning-agent' }],
    user: { _id: 'creator_4', name: 'Ana Díaz', avatarUrl: '/avatars/ana.png' },
    starredByCurrentUser: false,
    models: baseModels,
  },
  {
    _id: 'explore_proj_5',
    name: 'Resume Screener',
    status: 'stopped',
    stars: 112,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    incompleteIssues: 0,
    completeIssues: 25,
    repositories: [{ url: 'https://github.com/example/resume-screener' }],
    user: { _id: 'creator_5', name: 'Imran Noor', avatarUrl: '/avatars/imran.png' },
    starredByCurrentUser: false,
    models: {
      ...baseModels,
      medium: [{ provider: 'openrouter', model: 'command-r+' }],
    },
  },
  {
    _id: 'explore_proj_6',
    name: 'Video Summarization Tool',
    status: 'error',
    stars: 7,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    incompleteIssues: 6,
    completeIssues: 4,
    repositories: [{ url: 'https://github.com/example/video-summary' }],
    user: { _id: 'creator_6', name: 'Mei Lin', avatarUrl: '/avatars/mei.png' },
    starredByCurrentUser: true,
    models: baseModels,
  },
  {
    _id: 'explore_proj_7',
    name: 'Crypto Market Tracker',
    status: 'stopped',
    stars: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // recent
    updatedAt: new Date().toISOString(),
    incompleteIssues: 1,
    completeIssues: 0,
    repositories: [{ url: 'https://github.com/example/crypto-tracker' }],
    user: { _id: 'creator_7', name: 'Sam Gold', avatarUrl: '/avatars/sam.png' },
    starredByCurrentUser: false,
    models: {
      ...baseModels,
      backup: [{ provider: 'google', model: 'gemini-pro' }],
      medium: [
        { provider: 'google', model: 'gemini-flash-lite' },
        { provider: 'openai', model: 'chatgpt-o' },
        { provider: 'openrouter', model: 'r1-reasoner' },
      ]
    },
  },
  {
    _id: 'explore_proj_8',
    name: 'Legal Document Analyzer',
    status: 'stopped',
    stars: 58,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    incompleteIssues: 0,
    completeIssues: 14,
    repositories: [{ url: 'https://github.com/example/legal-analyzer' }],
    user: { _id: 'creator_8', name: 'Aisha Ali', avatarUrl: '/avatars/aisha.png' },
    starredByCurrentUser: false,
    models: baseModels,
  },
  {
    _id: 'explore_proj_9',
    name: 'Onboarding Buddy',
    status: 'starting',
    stars: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(), // recent
    updatedAt: new Date().toISOString(),
    incompleteIssues: 2,
    completeIssues: 0,
    repositories: [{ name: 'onboarding-buddy', isPrivate: false }],
    user: { _id: 'creator_9', name: 'Chris Nolan', avatarUrl: '/avatars/chris.png' },
    starredByCurrentUser: false,
    models: {
      ...baseModels,
      super: [{ provider: 'openai', model: 'gpt-4-turbo' }],
    },
  },
  {
    _id: 'explore_proj_10',
    name: 'Fitness Goal Tracker',
    status: 'running',
    stars: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
    incompleteIssues: 5,
    completeIssues: 2,
    repositories: [{ url: 'https://github.com/example/fitness-tracker' }],
    user: { _id: 'creator_10', name: 'Erin Matthews', avatarUrl: '/avatars/erin.png' },
    starredByCurrentUser: false,
    models: baseModels,
  },
  {
    _id: 'explore_proj_11',
    name: 'Podcast Summarizer',
    status: 'stopped',
    stars: 18,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    incompleteIssues: 1,
    completeIssues: 12,
    repositories: [{ url: 'https://github.com/example/podcast-summarizer' }],
    user: { _id: 'creator_11', name: 'Luca Romano', avatarUrl: '/avatars/luca.png' },
    starredByCurrentUser: false,
    models: {
      ...baseModels,
      utility: [{ provider: 'deepseek', model: 'deepseek-7b' }],
      medium: [
        { provider: 'anthropic', model: 'claude-3-opus' },
        { provider: 'openai', model: 'chatgpt-o' },
      ]
    },
  },
  {
    _id: 'explore_proj_12',
    name: 'Travel Recommendation Engine',
    status: 'running',
    stars: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(), // recent
    updatedAt: new Date().toISOString(),
    incompleteIssues: 3,
    completeIssues: 3,
    repositories: [{ url: 'https://github.com/example/travel-recommender' }],
    user: { _id: 'creator_12', name: 'Nora Chen', avatarUrl: '/avatars/nora.png' },
    starredByCurrentUser: false,
    models: baseModels,
  },
  {
    _id: 'explore_proj_13',
    name: 'AI Cooking Assistant',
    status: 'running',
    stars: 35,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    incompleteIssues: 2,
    completeIssues: 6,
    repositories: [{ url: 'https://github.com/example/cooking-assistant' }],
    user: { _id: 'creator_13', name: 'Olivia Grant', avatarUrl: '/avatars/olivia.png' },
    starredByCurrentUser: true,
    models: {
      ...baseModels,
      medium: [{ provider: 'google', model: 'gemini-pro' }],
    },
  },
];

export const FAKE_CARDS: SavedCard[] = [
  {
    id: 'pm_card_visa_1',
    brand: 'visa',
    last4: '4242',
    expiryMonth: 12,
    expiryYear: 2026,
    isDefault: true,
  },
  {
    id: 'pm_card_mc_2',
    brand: 'mastercard',
    last4: '4444',
    expiryMonth: 5,
    expiryYear: 2025,
    isDefault: false,
  },
  {
    id: 'pm_card_amex_3',
    brand: 'amex',
    last4: '3782',
    expiryMonth: 9,
    expiryYear: 2027,
    isDefault: false,
  },
  {
    id: 'pm_card_discover_4',
    brand: 'discover',
    last4: '6011',
    expiryMonth: 1,
    expiryYear: 2028,
    isDefault: false,
  },
];

export const FAKE_TRANSACTIONS: Transaction[] = [
  // 2022
  {
    _id: 'txn_2022_01',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 120.00,
    description: 'Initial account funding',
    stripeEventId: 'ch_2022_01',
    createdAt: new Date('2022-03-10T10:00:00Z').toISOString(),
    updatedAt: new Date('2022-03-10T10:00:00Z').toISOString()
  },
  {
    _id: 'txn_2022_02',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -40.00,
    description: 'Project: AI Writer',
    relatedProjectId: 'proj_x1',
    createdAt: new Date('2022-06-21T15:00:00Z').toISOString(),
    updatedAt: new Date('2022-03-10T10:00:00Z').toISOString()
  },
  

  // 2023
  {
    _id: 'txn_2023_01',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 200.00,
    description: 'Annual top-up',
    stripeEventId: 'ch_2023_01',
    createdAt: new Date('2023-01-05T09:30:00Z').toISOString(),
    updatedAt: new Date('2022-03-10T10:00:00Z').toISOString()
  },
  {
    _id: 'txn_2023_02',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -25.00,
    description: 'Project: Resume Parser',
    relatedProjectId: 'proj_4',
    createdAt: new Date('2023-02-02T10:10:00Z').toISOString(),
    updatedAt: new Date('2023-02-02T10:10:00Z').toISOString(),
  },
  {
    _id: 'txn_2023_03',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -60.00,
    description: 'Project: Podcast Summarizer',
    relatedProjectId: 'proj_11',
    createdAt: new Date('2023-05-05T08:20:00Z').toISOString(),
    updatedAt: new Date('2023-02-02T10:10:00Z').toISOString(),
  },

  // 2024
  {
    _id: 'txn_2024_01',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 90.00,
    description: 'Referral reward',
    createdAt: new Date('2024-03-10T09:00:00Z').toISOString(),
    updatedAt: new Date('2024-03-10T09:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_02',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -75.00,
    description: 'Project: Smart Meeting Notes',
    relatedProjectId: 'proj_2',
    createdAt: new Date('2024-05-10T09:45:00Z').toISOString(),
    updatedAt: new Date('2024-03-10T09:00:00Z').toISOString(),
  },

  // 2025
  {
    _id: 'txn_2025_01',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 40.00,
    description: 'Balance top-up',
    createdAt: new Date('2025-07-09T10:15:00Z').toISOString(),
    updatedAt: new Date('2024-03-10T09:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2025_02',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.PENDING,
    amount: -45.00,
    description: 'Project: Video Transcoder',
    relatedProjectId: 'proj_3',
    createdAt: new Date('2025-07-10T08:00:00Z').toISOString(),
    updatedAt: new Date('2024-03-10T09:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2025_03',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.FAILED,
    amount: -10.00,
    description: 'Project: HR Metrics Dashboard',
    relatedProjectId: 'proj_5',
    createdAt: new Date('2025-07-12T18:00:00Z').toISOString(),
    updatedAt: new Date('2024-03-10T09:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2025_04',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 30.00,
    description: 'Stripe refund',
    stripeEventId: 'ch_refund_001',
    createdAt: new Date('2025-07-15T10:00:00Z').toISOString(),
    updatedAt: new Date('2024-03-10T09:00:00Z').toISOString(),
  },

  {
    _id: 'txn_2024_12_01',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 50.00,
    description: 'Monthly subscription credit',
    createdAt: new Date('2024-12-01T08:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T08:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_02',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -5.00,
    description: 'Project: Quick Task 1',
    relatedProjectId: 'proj_quick_1',
    createdAt: new Date('2024-12-01T09:10:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T09:10:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_03',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -12.50,
    description: 'Project: Blog Post Draft',
    relatedProjectId: 'proj_blog_1',
    createdAt: new Date('2024-12-01T10:30:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T10:30:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_04',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -8.00,
    description: 'Project: Social Media Content',
    relatedProjectId: 'proj_social_1',
    createdAt: new Date('2024-12-01T11:45:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T11:45:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_05',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -20.00,
    description: 'Project: Market Research',
    relatedProjectId: 'proj_research_1',
    createdAt: new Date('2024-12-01T13:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T13:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_06',
    userId: 'test-user-id',
    type: TransactionType.CREDIT,
    status: TransactionStatus.SUCCEEDED,
    amount: 15.00,
    description: 'Bonus credit for survey completion',
    createdAt: new Date('2024-12-01T14:20:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T14:20:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_07',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -10.00,
    description: 'Project: Data Analysis',
    relatedProjectId: 'proj_data_1',
    createdAt: new Date('2024-12-01T15:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T15:00:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_08',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -15.00,
    description: 'Project: Report Generation',
    relatedProjectId: 'proj_report_1',
    createdAt: new Date('2024-12-01T16:15:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T16:15:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_09',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -5.00,
    description: 'Project: Quick Task 2',
    relatedProjectId: 'proj_quick_2',
    createdAt: new Date('2024-12-01T17:30:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T17:30:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_10',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -35.00,
    description: 'Project: E-commerce Strategy',
    relatedProjectId: 'proj_ecommerce_1',
    createdAt: new Date('2024-12-01T18:45:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T18:45:00Z').toISOString(),
  },
  {
    _id: 'txn_2024_12_11',
    userId: 'test-user-id',
    type: TransactionType.DEBIT,
    status: TransactionStatus.SUCCEEDED,
    amount: -7.50,
    description: 'Project: Content Calendar',
    relatedProjectId: 'proj_calendar_1',
    createdAt: new Date('2024-12-01T20:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T20:00:00Z').toISOString(),
  },
];
