import './globals.css';
import type { Metadata } from 'next';
import { AuthProvider } from '../lib/AuthContext';
import { Providers } from '../components/Providers'; // Import the new Providers component
import Header from '../components/Header'; // Import Header component

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
