// src/app/terms/page.tsx
import React from "react";

export default function TermsOfService() {
  return (
    // Using the same container classes as the Privacy Policy for consistency
    <div className="min-h-screen bg-background text-foreground flex justify-center p-4 sm:p-8">
      <div className="prose dark:prose-invert max-w-4xl w-full py-12">
        {/* Main Title */}
        <h2 className="text-center">Terms of Service for PromptToSoftware</h2>
        <p className="text-center text-muted-foreground">
          <strong>Last Updated:</strong> August 31, 2025
        </p>

        {/* Introduction */}
        <p>
          Welcome to PromptToSoftware ("we," "us," or "our"). These Terms of
          Service ("Terms") govern your access to and use of our website,{" "}
          <code>prompttosoftware.com</code>, and the services we provide
          (collectively, the "Service").
        </p>
        <p>
          By creating an account or using our Service, you agree to be bound by
          these Terms. If you do not agree to these Terms, you may not use the
          Service.
        </p>

        {/* Section 1 */}
        <h3>1. Description of Service</h3>
        <p>
          PromptToSoftware provides an autonomous AI-driven software development
          service. You provide a project description ("Prompt"), and our Service
          utilizes artificial intelligence to perform tasks such as creating
          repositories, writing code, running tests, and integrating with your
          existing development tools like GitHub and Jira.
        </p>
        <p>
          You acknowledge that the Service is experimental and the output is
          generated by AI. While our goal is to produce high-quality results,
          the generated code may contain bugs, errors, or unexpected results. You are responsible for reviewing,
          testing, and validating all code and other materials generated by the
          Service before use.
        </p>

        {/* Section 2 */}
        <h3>2. User Accounts</h3>
        <p>
          To use the Service, you must register for an account by authenticating
          with a third-party service (GitHub). You grant us permission to access
          your account information from GitHub as described in our Privacy
          Policy, including the ability to interact with your repositories on
          your behalf.
        </p>
        <p>
          You are responsible for all activities that occur under your account
          and for keeping your GitHub account credentials secure.
        </p>

        {/* Section 3 */}
        <h3>3. Payments, Billing, and Refunds</h3>
        <h4>A. Pricing Model</h4>
        <p>
          Our Service operates on a usage-based pricing model. Charges are
          calculated based on:
        </p>
        <ul>
          <li>
            <strong>Platform Fee:</strong> A flat hourly rate for each project
            while it is active and running.
          </li>
          <li>
            <strong>AI API Costs:</strong> The direct costs charged by
            third-party AI model providers for the API calls made on your
            behalf.
          </li>
        </ul>
        <p>
          You can provide your own API key for certain AI providers ("Bring Your
          Own Key"), in which case the corresponding AI API Costs will not be
          billed through our Service. You are responsible for all charges
          incurred with the provider directly.
        </p>

        <h4>B. Billing and Account Balance</h4>
        <p>
          The Service requires you to add funds to your account balance before
          starting a project. We use a third-party payment processor (Stripe) to
          handle all transactions. As your projects run, costs are deducted
          from your account balance in real-time. You are solely responsible for
          monitoring your usage and account balance. You can set cost and
          runtime limits within the Service to help manage your spending.
        </p>

        <h4>C. No Refunds Policy</h4>
        <p>
          <strong>
            All payments are final and non-refundable. When you add funds to
            your account, you are purchasing service credits that are consumed
            as you use the Service.
          </strong>
        </p>
        <p>
          Because our costs for compute resources and third-party AI APIs are
          incurred instantly, we cannot offer refunds for any used or unused
          funds in your account balance, including in cases of accidental usage
          or dissatisfaction with the generated output.
        </p>

        {/* Section 4 */}
        <h3>4. User Responsibilities and Conduct</h3>
        <p>You agree to use the Service in compliance with all applicable laws. You are solely responsible for:</p>
        <ul>
          <li>The Prompts and any other content you provide to the Service.</li>
          <li>
            Ensuring you have the necessary rights to any existing codebases you
            instruct the Service to modify.
          </li>
          <li>
            Reviewing and testing all code generated by the Service before
            deploying it to production environments.
          </li>
        </ul>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any illegal or malicious purpose.</li>
          <li>
            Attempt to reverse engineer, decompile, or otherwise discover the
            source code of the Service itself.
          </li>
          <li>
            Impose an unreasonable load on our infrastructure or interfere with
            the proper working of the Service.
          </li>
        </ul>

        {/* Section 5 */}
        <h3>5. Intellectual Property</h3>
        <ul>
          <li>
            <strong>Your Content:</strong> You retain full ownership of the
            Prompts you provide and the source code generated by the Service specifically for your projects ("Generated Code").
          </li>
          <li>
            <strong>Our Service:</strong> We and our licensors retain all
            ownership rights in and to the Service itself, including all related
            software, branding, and documentation.
          </li>
        </ul>

        {/* Section 6 */}
        <h3>6. Termination</h3>
        <p>
          You may stop using our Service and delete your account at any time. We
          reserve the right to suspend or terminate your access to the Service at
          our discretion, without notice, for any reason, including for a breach
          of these Terms. Upon termination, any remaining balance in your
          account is non-refundable.
        </p>

        {/* Section 7 */}
        <h3>7. Disclaimer of Warranties</h3>
        <p>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES
          OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE
          SERVICE OR THE GENERATED CODE WILL BE ERROR-FREE, SECURE, FIT FOR ANY
          PARTICULAR PURPOSE, OR MEET YOUR REQUIREMENTS. YOUR USE OF THE SERVICE
          IS AT YOUR OWN RISK.
        </p>

        {/* Section 8 */}
        <h3>8. Limitation of Liability</h3>
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW, PROMPTTOSOFTWARE, LLC SHALL
          NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
          OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER
          INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL,
          OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF THE SERVICE.
        </p>

        {/* Section 9 */}
        <h3>9. Changes to These Terms</h3>
        <p>
          We may modify these Terms from time to time. We will notify you of any
          changes by posting the new Terms on this page and updating the "Last
          Updated" date. Your continued use of the Service after any changes
          constitutes your acceptance of the new Terms.
        </p>

        {/* Section 10 */}
        <h3>10. Contact Us</h3>
        <p>
          If you have any questions about these Terms of Service, please contact
          us at:
        </p>
        <p>
          <a
            href="mailto:contact@prompttosoftware.com"
            className="text-primary hover:underline"
          >
            <strong>contact@prompttosoftware.com</strong>
          </a>
        </p>
      </div>
    </div>
  );
}
